backends:
  - name: cassandra-driver
    benchmark-name: insert
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh insert.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: concurrent_insert
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_insert.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: select
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh select.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: concurrent_select
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_select.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: batch
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh batch.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: paging
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh paging.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: concurrent_paging
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_paging.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: large_select
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh large_select.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: deser
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh deser.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: concurrent_deser
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_deser.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: ser
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh ser.js cassandra-driver

  - name: cassandra-driver
    benchmark-name: concurrent_ser
    build-command: npm install
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_ser.js cassandra-driver
