defaults:
  name: scylladb-driver
  build-command: npm run build

backends:
  - benchmark-name: insert
    run-command: ./benchmark/runner-config/run-js-benchmark.sh insert @scylladb/driver

  - benchmark-name: concurrent_insert
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_insert @scylladb/driver

  - benchmark-name: concurrency_parametrized_insert
    run-command: ./benchmark/runner-config/run-js-concurrency-benchmark.sh concurrent_insert @scylladb/driver

  - benchmark-name: select
    run-command: ./benchmark/runner-config/run-js-benchmark.sh select @scylladb/driver

  - benchmark-name: concurrent_select
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_select @scylladb/driver

  - benchmark-name: concurrency_parametrized_select
    run-command: ./benchmark/runner-config/run-js-concurrency-benchmark.sh concurrent_select @scylladb/driver

  - benchmark-name: batch
    run-command: ./benchmark/runner-config/run-js-benchmark.sh batch @scylladb/driver

  - benchmark-name: paging
    run-command: ./benchmark/runner-config/run-js-benchmark.sh paging @scylladb/driver

  - benchmark-name: concurrent_paging
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_paging @scylladb/driver

  - benchmark-name: concurrency_parametrized_paging
    run-command: ./benchmark/runner-config/run-js-concurrency-benchmark.sh concurrent_paging @scylladb/driver

  - benchmark-name: large_select
    run-command: ./benchmark/runner-config/run-js-benchmark.sh large_select @scylladb/driver

  - benchmark-name: deser
    run-command: ./benchmark/runner-config/run-js-benchmark.sh deser @scylladb/driver

  - benchmark-name: concurrent_deser
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_deser @scylladb/driver

  - benchmark-name: concurrency_parametrized_deser
    run-command: ./benchmark/runner-config/run-js-concurrency-benchmark.sh concurrent_deser @scylladb/driver

  - benchmark-name: ser
    run-command: ./benchmark/runner-config/run-js-benchmark.sh ser @scylladb/driver

  - benchmark-name: concurrent_ser
    run-command: ./benchmark/runner-config/run-js-benchmark.sh concurrent_ser @scylladb/driver

  - benchmark-name: concurrency_parametrized_ser
    run-command: ./benchmark/runner-config/run-js-concurrency-benchmark.sh concurrent_ser @scylladb/driver
