defaults:
  no-steps: 4
  step-progress: 4
  progress-type: multiplicative
  num-runs: 3
  measure: time
  timeout: "200s"

# We want to have the benchmark run for about 30-90 seconds at the highest step count.
# If, at some point (ex. due to driver optimizations), the benchmark starts to run faster,
# it's best to increase the default step count, to keep the benchmark results relevant and consistent.
# The last step is defined in each benchmark code file. Ex. for insert benchmark (insert.js):
# const iterCnt = stepCount || 400000;
# At this value the benchmark takes ~40 seconds to run. We then want to define the starting step in this config file.
# This definition should be picked in a way that matches the last step:
# Ex. insert: last step = starting step * (step-progress ** (no-steps - 1)) = 6250 * (4 ** 3) = 400000
# We chose 6250 as starting step, which is the exact value that sets the last step to 400000.

benchmarks:
  - name: insert
    starting-step: 6250
  - name: concurrent_insert
    starting-step: 62500
  - name: concurrency_parametrized_insert
    starting-step: 16
    step-progress: 2
    no-steps: 8
  - name: select
    starting-step: 1563
  - name: concurrent_select
    starting-step: 6250
  - name: concurrency_parametrized_select
    starting-step: 16
    step-progress: 2
    no-steps: 8
  - name: batch
    starting-step: 46875
  - name: paging
    starting-step: 63
  - name: concurrent_paging
    starting-step: 20
  - name: concurrency_parametrized_paging
    starting-step: 16
    step-progress: 2
    no-steps: 8
  - name: large_select
    starting-step: 63
  - name: deser
    starting-step: 32
  - name: concurrent_deser
    starting-step: 32
  - name: concurrency_parametrized_deser
    starting-step: 16
    step-progress: 2
    no-steps: 8
  - name: ser
    starting-step: 15
  - name: concurrent_ser
    starting-step: 19
  - name: concurrency_parametrized_ser
    starting-step: 16
    step-progress: 2
    no-steps: 8
