/* auto-generated by NAPI-RS. To modify the header, go to ./src/custom-types.d.ts */
/* eslint-disable */

// NAPI-RS does not properly generates types definitions for objects,
// with manual definitions of (To/From)NapiValue. For this reason,
// we manually define those types, in order to use them in the JS part of the code.

// ---------------------------------------------------------------------------
// Types for objects produced by define_rust_to_js_convertible_object.
// These are plain JS objects returned from Rust to JS
// ---------------------------------------------------------------------------

/** Information about a node in the ScyllaDB cluster. */
export interface HostWrapper {
  hostId: Buffer
  address: string
  datacenter: string | null
  rack: string | null
}

// ---------------------------------------------------------------------------
// Types for objects produced by define_js_to_rust_convertible_object.
// These are plain JS objects passed from JS into Rust (all fields optional).
// ---------------------------------------------------------------------------

/** TLS/SSL configuration passed to SessionOptions.sslOptions. */
export interface SslOptions {
  ca?: Array<string>
  cert?: string
  sigalgs?: string
  ciphers?: string
  ecdhCurve?: string
  honorCipherOrder?: boolean
  key?: string
  maxVersion?: TlsVersion
  minVersion?: TlsVersion
  passphrase?: string
  pfx?: string
  secureOptions?: bigint
  rejectUnauthorized?: boolean
}

/** Load-balancing configuration passed to SessionOptions.loadBalancingConfig. */
export interface LoadBalancingConfig {
  preferDatacenter?: string
  preferRack?: string
  tokenAware?: boolean
  permitDcFailover?: boolean
  enableShufflingReplicas?: boolean
  allowList?: Array<string>
}

/** Options for creating a new session via SessionWrapper.createSession. */
export interface SessionOptions {
  connectPoints?: Array<string>
  keyspace?: string
  applicationName?: string
  applicationVersion?: string
  clientId?: string
  credentialsUsername?: string
  credentialsPassword?: string
  cacheSize?: number
  sslOptions?: SslOptions
  loadBalancingConfig?: LoadBalancingConfig
  retryPolicy?: RetryPolicyKind
}

/** Per-query options passed to QueryOptionsWrapper. */
export interface QueryOptionsObj {
  autoPage?: boolean
  captureStackTrace?: boolean
  consistency?: number
  counter?: boolean
  fetchSize?: number
  isIdempotent?: boolean
  keyspace?: string
  logged?: boolean
  prepare?: boolean
  readTimeout?: number
  routingIndexes?: Array<number>
  routingNames?: Array<string>
  serialConsistency?: number
  timestamp?: bigint
  traceQuery?: boolean
}


///////////////////////////////////////////////
/* END OF CUSTOM TYPE DEFINITIONS.           */
/* All values below are generated by NAPI-RS */
///////////////////////////////////////////////
