name: Compile js-doc and build mdBook

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install --dev
      - name: Generate documentation
        run: npm run js-doc
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - run: mdbook build
        working-directory: ./docs
