# The goal of this workflow is to check if integration tests work correctly
# Currently it uses only datastax tests
name: Run integration tests
env:
  DEBUG: napi:*
  APP_NAME: scylladb-javascript-driver
  RUST_BACKTRACE: full
  PEDANTIC: true
  NO_CONCURRENCY: true
"on":
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build-and-run-tests:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npm run build -- --target x86_64-unknown-linux-gnu
    name: Build and run integration tests - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/common/setup
        with:
          host: ${{ matrix.settings.host }}
          target: ${{ matrix.settings.target }}
          node-version: 20
      - uses: ./.github/common/integration
        with:
          build-command: ${{ matrix.settings.build }}
